### ISSUE TITLE
Add OpenSearch description

### ISSUE THREAD

**Issue by brainwo** [mreichhoff/HanziGraph#41]
This helps adding search provider to a browser such as Mozilla Firefox, that can be used for creating a search shortcut.

https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by mreichhoff** [comment]
will take a look!

**Comment by mreichhoff** [comment]
Seems now to work for me on the main site...let me know of issues or other requests

**Comment by brainwo** [comment]
It does work nicely. There are two search provider, one for Simplified Chinese and one for Traditional Chinese, lovely idea. Thank you.
